
run:
  timezone: "America/New_York"
  output_dir: "data"
  dash_json: "docs/data/latest.json"

weights:
  # NEW high-value sources (phrases + search data)
  reddit_posts: 1.5        # Full post titles = actual blog topics!
  google_trends: 2.0       # ACTUAL search volume = most important signal
  
  # Original sources
  hackernews: 1.0
  hn_algolia: 1.1
  lobsters: 0.8
  devto: 0.7
  medium: 0.6
  stackoverflow_tags: 1.0
  homebrew: 0.9
  npm: 0.9
  github_trending: 1.2
  pypi: 0.9
  crates: 0.9

collectors:
  # ========================================
  # SAFE TESTING CONFIG
  # Disables risky sources that can block you
  # Safe to run every 5-10 minutes
  # ========================================
  
  # NEW: Reddit posts (SAFE - Keep enabled)
  reddit_posts:
    enabled: true
    subreddits: 
      - programming
      - webdev
      - learnprogramming
      - devops
      - javascript
      - python
      - rust
      - golang
      - MachineLearning
      - artificial
      - kubernetes
    time_filter: "week"
    limit: 30
    min_score: 50
  
  # RISKY: Google Trends (DISABLED for testing!)
  google_trends:
    enabled: false  # ← DISABLED - Can block IP if run too often
    keywords:
      - "cursor ai"
      - "anthropic claude"
      - "supabase"
      - "bun javascript"
      - "astro framework"
    timeframe: "today 3-m"
    geo: ""
  
  # SAFE sources - Keep enabled
  hackernews:
    enabled: true
    top_n: 150
  
  hn_algolia:
    enabled: true
    hours_back: 48
    min_points: 10
    hits_per_page: 200
  
  # RISKY: GitHub Trending (DISABLED for testing!)
  github_trending:
    enabled: false  # ← DISABLED - Can trigger captchas
    since: weekly
    languages: []
  
  # SAFE sources - Keep enabled
  lobsters:
    enabled: true
    endpoint: "https://lobste.rs/hottest.json"
    top_n: 150
  
  devto:
    enabled: true
    per_page: 80
    pages: 1
  
  medium:
    enabled: true
    topics: ["technology","programming","artificial-intelligence","data-science"]
  
  stackoverflow_tags:
    enabled: true
    site: "stackoverflow"
    top_n: 200
  
  homebrew:
    enabled: true
    window: "30d"
  
  npm:
    enabled: true
    packages: ["react","vue","svelte","next","vite","typescript","eslint","express","tailwindcss","axios"]
  
  pypi:
    enabled: true
    packages: ["requests","numpy","pandas","fastapi","django","flask","pytest","uvicorn","pydantic","scipy"]
  
  crates:
    enabled: true
    per_page: 100

